# SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Cypress Component Tests

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

concurrency:
  group: cypress-component-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_NAME: tables

jobs:
  component-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up node from version file
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build --if-present

      - name: Run component tests
        run: npm run tests:component

      - name: Upload test failure screenshots
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: failure()
        with:
          name: cypress-component-screenshots-node${{ matrix.node-version }}
          path: cypress/screenshots/
          retention-days: 5

      - name: Upload test videos
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: failure()
        with:
          name: cypress-component-videos-node${{ matrix.node-version }}
          path: cypress/videos/
          retention-days: 5

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest-low
    needs: component-tests

    if: always()

    name: cypress-component-summary

    steps:
      - name: Summary status
        run: if ${{ needs.component-tests.result != 'success' && needs.component-tests.result != 'skipped' }}; then exit 1; fi
